### PR TITLE
testing browsers

### PR DESCRIPTION
**Pull request by avishshah11**
Bot taking the audio and is saved in mp3 format in same directory but audio is not coming from bot.

### CODE REVIEW

**Review by HarshitRuwali — APPROVED** [review]
Fixed! And LGTM

**Review by HarshitRuwali — APPROVED** [review]
Fixed the bot's command voice.

**Comment by HarshitRuwali** [comment]
Wake up does not work. Removing it. And so the lock screen one(OS specific error).

**Comment by avishshah11** [comment]
ok

**Review by HarshitRuwali — APPROVED** [review]
Fixed all.

**Pull request merged**
